use crate::pkt::FieldName;

pub static FIELD_LENGTHS: &[(FieldName, usize)] = &[
    (FieldName::DevSessionId, 6),
    (FieldName::DevSequence, 8),
    (FieldName::DevPacketId, 8),
    (FieldName::DevPing, 1),
    (FieldName::InputSeq, 8),
    (FieldName::InputMvX, 6),
    (FieldName::InputMvZ, 6),
    (FieldName::InputYaw, 10),
    (FieldName::InputJump, 1),
    (FieldName::InputCrouch, 1),
    (FieldName::LocationX, 8),
    (FieldName::LocationZ, 8),
    (FieldName::ColorH, 6),
    (FieldName::ColorS, 3),
    (FieldName::ColorV, 3),
    (FieldName::DevIsNewPlayer, 1),
    (FieldName::Health, 3),
    (FieldName::PlayerCount, 4),
    (FieldName::IsJumping, 1),
    (FieldName::IsCrouching, 1),
    (FieldName::IsFriendly, 1),
];
